apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ${project_name}
spec:
  selector:
    matchLabels:
      app: taskcluster
      tc-service: ${project_name}
      tc-proc: web
  replicas: 1 # TODO: make configurable
  template:
    metadata:
      labels:
        app: taskcluster
        tc-service: ${project_name}
        tc-proc: web
    spec:
      containers:
      - name: ${project_name}
        image: ${docker_image}
        imagePullPolicy: Always
        resources:
          # TODO: Make configurable
          requests:
            cpu: 100m
            memory: 400Mi
        env:
          $flatten:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: ${root_url}
            - $map: {$eval: "secret_keys"}
              each(k):
                name: '${k}'
                valueFrom:
                  secretKeyRef:
                    name: '${secret_name}'
                    key: '${k}'
        ports:
        - containerPort: 80
