language: go

go:
  - 1.4

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64

install:
  - go get -d -v ./...

script:
  - go install -v ./...
  - test "${GOARCH}" == "linux" && go vet ./...
  - go test ./...

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      - "irc.mozilla.org#taskcluster-bots"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
