language: go

go:
  # this is a lie - we will use 1.7 which isn't supported yet
  # by downloading it later in "before_install" section
  # we use 1.7 due to https://github.com/contester/runlib/issues/5#issuecomment-241419381
  # which could have also been achieved via vendoring an older version, but for let's
  # keep up-to-date with latest version
  - 1.6

before_install:
  - curl -o go.tar.gz -sL https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz
  - tar -C $HOME -xf go.tar.gz
  - rm go.tar.gz
  - export GOROOT="${HOME}/go"
  - export PATH="${GOROOT}/bin:${PATH}"
  - go version
  - go env
  - go get github.com/mattn/goveralls

script:
  - ./build.sh

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.report -service=travis-ci

# encrpyt channel name to get around issue
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      # encrpyted string was "irc.mozilla.org#taskcluster-bots"
      - secure: "EcOYIepqv18ohTPA3rMkHyUCcKzwSGoSrmJoWYksWJYuwbnIMqYsLbgqY8AOkxD/okPMbj3mBAArAo4mRutGWrsCQQrBBK9hxIhj3abdBf6120EjUSWOTdIFIkmSepQeat6/8KJONkSwyCBjnjPs3bhSH1hYY1qsRrHo8g2OUJI="
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
