language: go

go:
  - 1.4
  - tip

before_script:
  - go generate ./...
  - echo "GO version: ${TRAVIS_GO_VERSION}"

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      - "irc.mozilla.org#tcclient-go"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
