language: go

go:
  - 1.4

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/pierrre/gotestcover

script:
  - ./build.sh -d

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.report -service=travis-ci

# encrpyt channel name to get around issue
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      # encrpyted string was "irc.mozilla.org#taskcluster-bots"
      - secure: "EcOYIepqv18ohTPA3rMkHyUCcKzwSGoSrmJoWYksWJYuwbnIMqYsLbgqY8AOkxD/okPMbj3mBAArAo4mRutGWrsCQQrBBK9hxIhj3abdBf6120EjUSWOTdIFIkmSepQeat6/8KJONkSwyCBjnjPs3bhSH1hYY1qsRrHo8g2OUJI="
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
