language: go
sudo: false
go:
- 1.5
env:
  - "GIMME_OS=linux GIMME_ARCH=amd64"
  - "GIMME_OS=darwin GIMME_ARCH=amd64"
  - "GIMME_OS=windows GIMME_ARCH=amd64"
  - "GIMME_OS=windows GIMME_ARCH=386"
before_install:
# workaround for travis-ci/gimme#25 to pick up latest version of gimme and run again
- curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
- chmod u+x gimme
- unset GOROOT GOTOOLDIR
- eval "$(./gimme 1.5)"
- go version
- go env
# end of workaround ###
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get github.com/pierrre/gotestcover
script:
# need to test without gotestcover since error code is not reliable for gotestcover
- "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || go test -v ./..."
after_script:
# using gotestcover means tests get run again, but need to do this since exit code of gotestcover is unreliable
- "if test $GIMME_OS.$GIMME_ARCH = linux.amd64; ${GOPATH}/bin/gotestcover -v -coverprofile=coverage.report ./...; go tool cover -func=coverage.report; ${HOME}/gopath/bin/goveralls -coverprofile=coverage.report -service=travis-ci; fi"
notifications:
  irc:
    channels:
    - secure: aYfRwI+g4L9xkUXXKWFx7TuR4TojGVjnUWEx74TvrrAeNqJd1+9vZdtohncQxvArpx0gRHVfVc6n2AZoBNUgo2dSqTBWVwtUQfGf0JyQddS6MdTJzHS2aoNgGRWUwRznjZzloD0eZZfeW+/nbYsfSS12Edl3YNT4X8/rhlHVtO4=
    on_success: change
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'
before_deploy:
- source .travis_rename_releases.sh
deploy:
  provider: releases
  api_key:
    secure: F5o1RQ4jvj0DimxDPa+bOzThpzYlsyzs0jh30o9dsXYEJFYBwTWQlAmveP1ImWsRSnVe09qVkrIpICMSTdEgqSBJx9I7nEjDqgu3gzdQVFl8sA40WeHNkb7xYxADUuUdx2ABgt13/LoTLzPhR5L54eQ6FdWjlWeKU/zW54ppS84=
  file:
    - "${RELEASE_FILE}"
  on:
    repo: taskcluster/taskcluster-proxy
    tags: true
  skip_cleanup: true
