---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${project_name}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${project_name}-secrets-read
rules:
- apiGroups: ['']
  resources: ['secrets/${project_name}']
  verbs: ['get', 'watch', 'list']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${project_name}-secrets-read
subjects:
- kind: User
  name: ${project_name}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ${project_name}-secrets-read
  apiGroup: rbac.authorization.k8s.io
