defaults:
  app:
    # the URL at which this service will be available, without a trailing `/`
    publicUrl: !env PUBLIC_URL
    sessionSecretKey: !env SESSION_SECRET_KEY
    loginStrategies: !env:list LOGIN_STRATEGIES
    # if true, serve the /playground path
    playground: false

  monitoring:
    enable: !env:bool MONITORING_ENABLE
    pretty: !env:bool PRETTY_LOGGING
    level: !env LEVEL

  # Server configuration
  server:
    # Port to listen for requests on
    port: !env:number PORT

  # Configuration of access to other taskcluster components
  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN

  # Pulse credentials
  pulse:
    namespace: !env PULSE_NAMESPACE
    username: !env PULSE_USERNAME
    password: !env PULSE_PASSWORD
    hostname: !env PULSE_HOSTNAME
    vhost: !env PULSE_VHOST

  # config for the github login strategy
  githubLogin:
      # client ID and secret for the github OAuth application
    clientId: !env GITHUB_CLIENT_ID
    clientSecret: !env GITHUB_CLIENT_SECRET

  # config for the mozilla auth0 login provider
  mozillaAuth0Login:
    domain: !env MOZILLA_AUTH0_DOMAIN
    # client ID and secret for the github OAuth application
    clientId: !env MOZILLA_AUTH0_CLIENT_ID
    clientSecret: !env MOZILLA_AUTH0_CLIENT_SECRET
    audience: !env MOZILLA_AUTH0_AUDIENCE
    scope: !env MOZILLA_AUTH0_SCOPE

development:
  app:
    # this assumes that taskcluster-ui's dev server is running on port 5080
    publicUrl: http://localhost:5080
    sessionSecretKey: i-like-cats
    loginStrategies: []
    playground: true
  server:
    # taskcluster-ui's dev server assumes port 3050
    port: 3050
  monitoring:
    level: warning
    enable: false

production:
  pulse:
    namespace: taskcluster-web-server
