defaults:
  taskcluster:
      rootUrl: ...
  pulse:
    namespace:
    username: ..
    password: ..
    hostname: ..
    vhost: ..
  login:
    strategies:
      github-oauth2:
        clientId: ...
        clientSecret: ...
