apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ${project_name}
spec:
  selector:
    matchLabels:
      app: taskcluster
      tc-service: ${project_name}
      tc-proc: web
  replicas: 1 # TODO: make configurable
  template:
    metadata:
      annotations:
        secrets_hash: ${secrets_hash}
      labels:
        app: taskcluster
        tc-service: ${project_name}
        tc-proc: web
    spec:
      serviceAccountName: ${project_name}
      containers:
      - name: ${project_name}
        image: ${docker_image}
        imagePullPolicy: Always
        args: [web]
        resources:
          # TODO: Make configurable
          requests:
            cpu: 50m
            memory: 100Mi
        env:
          $flatten:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: ${root_url}
            - $map: {$eval: 'secret_keys'}
              each(k):
                name: '${k}'
                valueFrom:
                  secretKeyRef:
                    name: '${secret_name}'
                    key: '${k}'
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/${service_name}/v1/ping # TODO: configurable
            port: 80
          timeoutSeconds: 5
          periodSeconds: 10
          initialDelaySeconds: 3
