repositories:

# workers
- name: docker-worker
  kind: other
  docs:
    tier: workers
  source: https://github.com/taskcluster/docker-worker#master

- name: generic-worker
  kind: other
  docs:
    tier: workers
  source: https://github.com/taskcluster/generic-worker#master
