---
repositories:

# services

# microservices
- name: auth
  kind: service
  source: monorepo
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: queue
  kind: service
  source: monorepo
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: index
  kind: service
  source: monorepo
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: purge-cache
  kind: service
  source: monorepo
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: github
  kind: service
  source: monorepo
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: login
  kind: service
  source: monorepo
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: hooks
  kind: service
  source: monorepo
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: secrets
  kind: service
  source: monorepo
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: notify
  kind: service
  source: monorepo
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: gce-provider
  kind: service
  source: https://github.com/imbstack/taskcluster-gce-provider-concept#master
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

- name: events
  kind: service
  source: https://github.com/taskcluster/taskcluster-events#master
  docs: generated
  service:
    buildtype: heroku-buildpack
    stack: heroku-16
    buildpack: https://github.com/heroku/heroku-buildpack-nodejs

# docs
- name: docs
  kind: service
  docs:
    tier: integrations
    projectName: taskcluster-docs
  service:
    buildtype: docs
    node: 9
  source: https://github.com/taskcluster/taskcluster-docs#master

# tools
- name: tools
  kind: service
  docs:
    tier: integrations
    projectName: taskcluster-tools
  service:
    buildtype: tools-ui
    node: 10
  source: https://github.com/taskcluster/taskcluster-tools#master

# references (and schemas)
- name: references
  kind: service
  docs:
    tier: integrations
    projectName: taskcluster-references
  service:
    buildtype: references
    node: 8
  source: https://github.com/taskcluster/taskcluster-references#master

# docs/metadata sources that are not compiled into the final product

# workers
- name: docker-worker
  kind: other
  docs:
    tier: workers
  source: https://github.com/taskcluster/docker-worker#master

- name: generic-worker
  kind: other
  docs:
    tier: workers
  source: https://github.com/taskcluster/generic-worker#master
