$schema: "/schemas/common/metaschema.json#"
title: "Worker Configuration Testing"
description: |
  Request body for testing a worker configuration
type: object
properties: 
  workerConfiguration: {$ref: 'worker-configuration.json#'}
  satisfiers: {$ref: 'satisfiers.json#'}
additionalProperties: false
required:
  - workerConfiguration
  - satisfiers
